language: rust
rust:
  # - stable
  - nightly
cache: cargo
script:
  - cargo build
  - cargo test
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo fmt -- --check
  - cargo clippy


